spring.application.name=bank_core_api

spring.datasource.url=jdbc:mysql://localhost:3306/banco_bff?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=user_ADMIN1

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
